### ISSUE TITLE
BeforeRender field removes or alter code after saving

### ISSUE THREAD

**Issue by NativoDigital** [Octopoos/SEBLOD#632] opened 2022-01-11 16:54 UTC
Hi,
Since one of the last updates when editing or adding this field in free mode, after saving, a lot of code is changed or removed. So is not possible to edit an existing one or create a new one.
Best regards.

**Comment by sebastienheraud** [comment] 2022-01-11 17:05
Hi,
Thanks, will check/fix before the next release.
Saba

**Comment by sebastienheraud** [comment] 2022-01-31 16:49
Hi,

There was indeed a regression from 3.21 to 3.21.4 (included), but this should be fixed since 3.21.5 with https://github.com/Octopoos/SEBLOD/commit/787b44ac4e6aaa00a48046d5d62dd31ca602aca1

Please make sure your site is up-to-date and confirm.

We tried with the following code, and nothing was removed:
```
$fields['art_title']->typo = str_replace( '<h3', '<h3 class="toto"', $fields['art_title']->typo );

$fields['city_snippet']->typo = '<p><em>The snippet has been removed.</em></p>';
```

Feel free to share additional info.

Thanks,
Saba

**Comment by NativoDigital** [comment] 2022-01-31 17:45
Hey! Sorry... I'm not sure what happened. Site is and was up to date, Seblod 3.21.5 and Joomla 3.10.5. Today I tried again with your snippet and it works ok. I tried also with my original snippet and also works. The only understandable explanation is that I had a problem with the browser cache 20 days ago.

**Comment by sebastienheraud** [comment] 2022-01-31 17:47
Thanks @NativoDigital for the feedback :)

**Closed** 2022-01-31 17:46 UTC
