### ISSUE TITLE
Only 1 result in seb_blog template used with the list field

### ISSUE THREAD

**Issue by Octopoos-James** [Octopoos/SEBLOD#42] opened 2015-04-09 16:51 UTC
When seb_blog is used as the list template within a list field, it will only display 1 result. If seb_table or seb_list is used, there is no issue.

Issue originally reported and confirmed here - with some further debugging information as well: http://www.seblod.com/community/forums/standard-premium-memberships/seblod-list-plugin-always-returns-only-1-item

**Comment by pulsarinformatique** [comment] 2015-06-24 09:53
Hi

any update on this issue please ?
thanks

cyril

**Comment by olivier-at-octopoos** [comment] 2015-06-25 12:36
Hi Cyril,

At least, we've found what the problem is.
We're still checking how we can handle this without breaking anything.

Olivier

**Comment by designbengel** [comment] 2015-11-24 08:49
I have this issue too :) following thread

**Comment by sebastienheraud** [comment] 2016-02-23 12:22
Hi,
This is fixed in the "master".
Will be included in upcoming SEBLOD 3.8.0 release.
Saba.

**Closed by sebastienheraud** 2016-02-23 12:22 UTC
