### ISSUE TITLE
Error 404 : check availability of title via ajax with single quote 

### ISSUE THREAD

**Issue by pierre-H** [Octopoos/SEBLOD#295] opened 2016-10-26 13:25 UTC
Hi,
Thank you for your great work.
I've got an availability check on a title field via ajax.
When there is a single quote (') in the title, I've got a 404 error.
The url islike this : 
`www.mywebsite.com/index.php?option=com_cck&task=ajax&format=raw&file=/plugins/cck_field_validation/ajax_availability/assets/ajax/script.php&fieldId=title&fieldValue=test+d%2527single+quote&avTable=content&avColumn=title&_=1477487853239`

It's because of d%2527 I think ...

I use Joomla 3.6.4 and Seblod 3.10.0

Thanks

**Comment by klas** [comment] 2016-11-08 10:08
I can't reproduce this issue with current Seblod 3.10

This is most likely mod_security or similar protection system blocking url on the server.

**Comment by sebastienheraud** [comment] 2017-08-25 08:29
Hello,
Not able to replicate.
I'm closing it now. If needed, please use our forums.
Regards,
Saba.

**Closed by sebastienheraud** 2017-08-25 08:29 UTC
