### ISSUE TITLE
Broken language files

### ISSUE THREAD

**Issue by kkaazzoo** [Octopoos/SEBLOD#648] opened 2022-08-13 06:55 UTC
Hi, language files broken after upgrading to SEBLOD 4.0.0 Release Preview 3

![image](https://user-images.githubusercontent.com/19167244/184472677-631e54c3-81bd-441c-816a-292ce34f672f.png)

**Comment by sebastienheraud** [comment] 2022-08-13 07:27
Hi @kkaazzoo,
Upgrading from Release Preview 2 or other?
Was there an error after the upgrade?
Thanks,
Saba

**Comment by kkaazzoo** [comment] 2022-08-13 07:52
@sebastienheraud 
Upgrading from Release Preview 2.
No errors after update.

**Comment by viocassel** [comment] 2022-08-13 08:26
Hi @sebastienheraud @kkaazzoo ,
this happens if the Joomla Administrator interface is different from English language.

**Comment by sebastienheraud** [comment] 2022-08-13 11:35
Hi @viocassel,
> this happens if the Joomla Administrator interface is different from English language.
Ah OK! Thanks will try with French 😄 
Saba

**Comment by greifbar** [comment] 2022-08-14 13:02
Same problem here :) Update from Preview 2 to 3 without any errors. Backend-language was German :)

**Comment by greifbar** [comment] 2022-08-25 07:32
@sebastienheraud same after upgrading to Preview 4

**Comment by sebastienheraud** [comment] 2022-08-25 07:32
Yes indeed, not checked yet.

**Comment by sebastienheraud** [comment] 2022-08-25 07:34
Note: people could start creating new language packs with the new naming (no xx-XX in filenames), thus the core would not have to process those. 
Saba

**Comment by aalisg** [comment] 2022-09-02 14:22
Hello,

We have the same problem with the website we are developing (Joomla! 4.2.1 and Seblod 4 Release Preview 4). Is there a way to fix it?

Regards,

**Comment by vampsm** [comment] 2022-09-08 11:04
https://github.com/Octopoos/SEBLOD/issues/653#issuecomment-1240564381

**Comment by kimbare** [comment] 2022-10-01 00:16
I have been having this same problem every since I put Seblod 4.0.1 Release.Preview.4 on a Joomla 4 website.  I just updated to SEBLOD Version 4.0.1 Release.Preview.5, the website is Joomla 4.2.3 and this is how it still looks.  When will there be a fix for this?

![broken language files in Seblos 4 0 1 preview 5](https://user-images.githubusercontent.com/24217410/193374477-9650a381-fba4-465d-a147-5e9ab954f9d8.jpg)

**Comment by Ilya-Zhulin** [comment] 2022-10-17 04:14
The same thing after fresh installation SEBLOD rp6 to Joomla 4.2.3

**Comment by sebastienheraud** [comment] 2023-03-15 03:13
Hi all,
Could you please share the Joomla! package you install, and the steps to replicate.
Is it one Joomla package that comes WITHOUT english language?
Not able to replicate so far.
Thanks,
Saba

**Comment by joomleb** [comment] 2023-03-16 00:56
Hi guys, Hi @sebastienheraud 
I suppose this can be related, so I'm going to comment here.
On December I reported this languages bug to Joomla 4.x https://github.com/joomla/joomla-cms/issues/39386

Two days ago I had back the same bug upgrading a site from Joomla 3.10.11 to:
PHP 7.4.33 + MariaDB 10.5.15 + Joomla 4.2.9 + Seblod 4.0.2 p8
Here an image as example for you:
![Bug-English-Spanish](https://user-images.githubusercontent.com/14607633/225480469-d63c386c-4504-438b-852c-3a46d8d3dd1f.png)


The Bug disappeared when I disabled, through the Joomla Manager, all the "Seblod" Component/Plugins/Modules etc.

Thinking to investigate exactly which Extension was the cause, I mass enabled again all the disabled "Seblod" Extensions and the site crashed giving me back this detailed error messages:
- [Exceptions](https://photos.app.goo.gl/PSYFjGr4szD5ztbv6)
- [Stack Traces](https://photos.app.goo.gl/tmq5BaJaDfogDWhb6)

Please, How can I restore the site which is currently inaccessible ?

**Comment by kkaazzoo** [comment] 2023-03-16 09:18
> Hi all, Could you please share the Joomla! package you install, and the steps to replicate. Is it one Joomla package that comes WITHOUT english language? or clarify when/which language is enable during Joomla! install or prior SEBLOD install/update (admin or site)? Not able to replicate so far. Thanks, Saba

Hi, Saba,

Stages

1. I installed Joomla 4.2.9,

2. Then I installed a package with the Russian language.

3. Then, in the Joomla control panel, I assigned Russian as the default language for the administrative part and for the front part of the site.

4. Installed seblod 4.0.2 Release Preview 8

Got a problem with broken Seblod language files

**Comment by coolcat-creations** [comment] 2023-03-16 10:12
Here is a screensharing of a fresh install I installed 3.10 to replicate my upgrade process.
1) Installed Seblod (old Version)
2) forgot to install german so I did
3) upgraded Seblod
4) switched backend to german
5) upgraded to joomla 4 all language strings are broken

https://vimeo.com/808628723

**Comment by sebastienheraud** [comment] 2023-04-15 07:38
Hi All,
Thanks for all info.
The "default language" behaviour seems to have changed in Joomla! 4, which does not load english files anymore when local files are not installed.
We applied a workaround as a fallback (hopefully no side effect...).
Feel free to have a try using https://github.com/Octopoos/SEBLOD/releases/tag/4.0.0-rp9
Saba

**Comment by kkaazzoo** [comment] 2023-04-15 08:39
> Hi All, Thanks for all info. The "default language" behaviour seems to have changed in Joomla! 4, which does not load english files anymore when local files are not installed. We applied a workaround as a fallback (hopefully no side effect...). Feel free to have a try using https://github.com/Octopoos/SEBLOD/releases/tag/4.0.0-rp9 Saba

Hi, Saba. Already better. But the problem is not completely solved

![image](https://user-images.githubusercontent.com/19167244/232201191-435c563e-cc10-408f-9b6c-62009f171666.png)
![image](https://user-images.githubusercontent.com/19167244/232201226-fda0cd3b-581a-41b4-b96d-545648dcb2aa.png)

**Comment by coolcat-creations** [comment] 2023-04-15 09:35
Same here, the update did not solve the issues.

<img width="811" alt="grafik" src="https://user-images.githubusercontent.com/828371/232205746-eabafdb8-448d-4e92-b5bb-5260ae150f2b.png">
<img width="338" alt="grafik" src="https://user-images.githubusercontent.com/828371/232205757-c7045874-63bf-4695-94b7-df9ede80b6f0.png">

<img width="433" alt="grafik" src="https://user-images.githubusercontent.com/828371/232205813-f82ff622-325c-476c-a9b1-0c41dfb44e8e.png">

<img width="1183" alt="grafik" src="https://user-images.githubusercontent.com/828371/232205834-9e407b23-b2a2-47b7-99ba-ad23ebd6da4f.png">

**Comment by joomleb** [comment] 2023-05-05 02:37
Hi @sebastienheraud 
Please, Is there any news about this Bug fixing ?

**Comment by coolcat-creations** [comment] 2023-05-05 06:14
There will be a new release today I hope it fixes it

**Comment by sebastienheraud** [comment] 2023-05-05 19:27
Hi @kkaazzoo,
Thank you for replying with details about improvements and remaining issues. Appreciated!
The workaround is applied on Plug-ins with the latest package.
Templates & Variations (and the Nav Item _com_cck_core_title_) will be done on the next one.
Saba

**Comment by joomleb** [comment] 2023-05-05 21:53
@sebastienheraud 
PHP 7.4.33 + MariaDB 10.5.15 + Joomla 4.3.1 + Seblod 4.0.3

Nothing is changed, I still have back the same issue as described [above](https://github.com/Octopoos/SEBLOD/issues/648#issuecomment-1471109399)

**Comment by sebastienheraud** [comment] 2023-05-09 08:35
@kkaazzoo Templates & Variations https://github.com/Octopoos/SEBLOD/commit/dab2f8c23771c08c4ce211d614d9113e9754d52c

**Comment by sebastienheraud** [comment] 2023-05-15 17:32
Hi,
SEBLOD 4.0.4 should be release tomorrow. 
Note: we may have found the root cause (and will rollback workarounds fixes and/or add one additional parameter to control)
Saba

**Comment by kkaazzoo** [comment] 2023-05-19 17:04
> Hi, SEBLOD 4.0.4 should be released tomorrow. Note: we may have found the root cause (and will rollback workarounds and/or add one additional parameter to control) Saba

Hi, @sebastienheraud 

I no longer see this problem. I suppose the topic can be closed if other users have also solved it.

**Comment by sebastienheraud** [comment] 2023-05-24 23:01
Thanks @joomleb

**Closed by sebastienheraud** 2023-05-24 23:01 UTC
