### ISSUE TITLE
jquery compatibility

### ISSUE THREAD

**Issue by HarryBosh** [Octopoos/SEBLOD#180] opened 2016-04-21 05:33 UTC
I have had to add this to my template as the file.upload script is out of date with a newer jquery

`<script type="text/javascript">
                    if (typeof jQuery.fn.live == 'undefined' || !(jQuery.isFunction(jQuery.fn.live))) {
                        jQuery.fn.extend({
                                live: function (event, callback) {
                                     if (this.selector) {
                                                jQuery(document).on(event, this.selector, callback);
                                        }
                                }
                        });
                    }
                </script>`

**Comment by HarryBosh** [comment] 2016-04-21 05:34
REgarding the .live function

**Comment by klas** [comment] 2016-11-06 11:15
I can't reproduce this issue with current Seblod 3.10. Has been fixed during cleanup.

**Comment by sebastienheraud** [comment] 2016-11-07 10:54
I'm closing it.
Thanks.

**Closed by sebastienheraud** 2016-11-07 10:54 UTC
