### ISSUE TITLE
Ajax's validation issue

### ISSUE THREAD

**Issue by salahjaafar** [Octopoos/SEBLOD#659] opened 2022-09-28 11:04 UTC
Ajax's validation problem when filling out a form using seblod_4.0.1.Release.Preview.4.zip the message remains displayed.
![Screenshot 2022-09-28 at 10-01-41 Ajouter](https://user-images.githubusercontent.com/47123877/192763542-98a268f3-c89a-4b11-bdab-12a69343b6bb.png)

**Comment by sebastienheraud** [comment] 2022-09-29 21:31
Hi Salah,

Thank you for reporting.
This seems to be a regression since Release Preview 3.
It is fixed in upcoming Release Preview 5.

Saba

**Closed by sebastienheraud** 2022-09-29 21:31 UTC

**Comment by salahjaafar** [comment] 2022-10-02 20:23
Thanks, I tested Release Preview 5 and it works fine.
