### ISSUE TITLE
Error count). Argument # (Svalue) must be of type Countablelarray, null given Seblod 3.23.1 and 3.23.2

### ISSUE THREAD

**Issue by coolcat-creations** [Octopoos/SEBLOD#694] opened 2023-03-01 08:36 UTC
I have this error:
count(). Argument # (Svalue) must be of type Countablelarray, null given
Function Location
O JROOT/libraries/cck/base/list/list_inc.php:459
include() JROOT/plugins/cck_field/cck_list/cck_list.php:364
plgCCK_FieldCck_List::_render0) JROOT/plugins/cck_field/cck_list/cck_list.php:205
#HNN TOON co plgCCK_FieldCck_List::onCCK_FieldBeforeRenderContent0) JROOT/Libraries/cms/cck/cck.php:32
JCck::callFunc_Array) JROOT/plugins/content/cck/cck.php:595
plgContentCCK-_render( JROOT/plugins/content/cck/cck.php:444
plgContentCCK->_prepare() JROOT/plugins/content/cck/cck.php:274
plgContentCCK->onContentPrepare() JROOT/libraries/joomla/event/event.php:70
9 JEvent->update() JROOT/libraries/joomla/event/dispatcher.php:160
10 JEventDispatcher-»trigger() JROOT/libraries/cms/html/content.php:41

**Comment by sebastienheraud** [comment] 2023-06-13 11:56
Hi Elisa,
This fix https://github.com/Octopoos/SEBLOD/commit/27d5e76ae103edb20a983d52880f4024c34d2adb will be including in upcoming package.
The root cause here is another story has we have not enough details/context.
Saba

**Closed by sebastienheraud** 2023-06-13 11:56 UTC
