### ISSUE TITLE
Joomla Login Module redirect Links broken when used with seblod

### ISSUE THREAD

**Issue by designbengel** [Octopoos/SEBLOD#46] opened 2015-05-06 15:27 UTC
By using the default joomla login module the redirects which are set in module settings are broken.

For example in my case the home item is set but the module redirects to /?search=categories&task=search after login.

Also tested on clean Joomla install without issues. By adding Seblod to the clean installation environment it´s broken. For example by selecting to redirect to the Demo Page "About" it redirects to "/component/content/article.html?id=1" instead of about.html. 

Issue in Joomla 3.4.1 with Seblod 3.5.1

**Comment by Octopoos-James** [comment] 2015-05-06 15:39
I can confirm that this is a bug. It's only an issue with the Joomla Login Module redirection when SEBLOD is installed, it is not an issue with the Joomla Login Menu Item.

**Comment by sebastienheraud** [comment] 2015-05-24 15:02
Hi,
For what I've seen/tested... the login module redirection is broken even if SEBLOD is not installed.
Let's dig further at the J & Beyond.
Regards,
Saba.

**Comment by Mat-o** [comment] 2015-05-31 06:54
Hi,
the bug is in Joomla 3.4.1. Here is the fix (due to 3.4.2) :
https://github.com/joomla/joomla-cms/pull/6542/files

-mato

**Comment by sebastienheraud** [comment] 2015-05-31 08:44
Hi Mato,
Thanks for sharing this. And yes I can confirm.
Issue is fixed.. I'm closing it.
Saba.

**Closed by sebastienheraud** 2015-05-31 08:44 UTC
