### ISSUE TITLE
Category with empty Alias causes JLIB_DATABASE_ERROR_CATEGORY_UNIQUE_ALIAS all the time

### ISSUE THREAD

**Issue by jochendaum** [Octopoos/SEBLOD#222] opened 2016-06-10 02:30 UTC
Hi,

version 3.8.1 on Joomla 3.5.1

we've experienced that we cannot upload documents with the file upload field. We also get a message JLIB_DATABASE_ERROR_CATEGORY_UNIQUE_ALIAS / "Another category with the same parent category has the same alias (remember it may be a trashed item)." every time we save any article.

Through debugging I found:
- We had a trahsed category with an empty alias.

plugins/cck_storage_location/joomla_category/joomla_category.php is called when article is saved and line 365 then saves a category with id=null.

Happy to provide test system for you, if this helps.

**Comment by klas** [comment] 2016-11-07 06:57
I can't reproduce this issue with current Seblod 3.10 - has been fixed by adding a prefix to the category alias when alias already exists

**Closed** 2016-11-07 11:37 UTC
