### ISSUE TITLE
Article Tags field conflict with validation js on front end

### ISSUE THREAD

**Issue by krj10** [Octopoos/SEBLOD#139] opened 2016-02-01 13:47 UTC
Validation tooltip just stop to work if we put a Article Tag field on front end.

Might as well check back end too.

(Ignore other js errors on image they are not related with this issue, this error happens too on firefox without any extension)

![seblod](https://cloud.githubusercontent.com/assets/17006496/12719004/8c58f6a4-c8d9-11e5-906d-252bfde33ab6.PNG)

**Comment by klas** [comment] 2016-10-10 11:15
I can't reproduce this issue with current Seblod 3.9.2. I would say issue comes from your custom javascripts.

**Comment by sebastienheraud** [comment] 2016-11-07 11:01
I'm closing it.
If needed please re-open.
Thanks.

**Closed by sebastienheraud** 2016-11-07 11:01 UTC
